name: Build YTMusicUltimate IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug directory structure
      run: |
        echo "Current directory: $PWD"
        ls -la
        echo "Podfile location:"
        find . -name Podfile -print || echo "No Podfile found"

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.0

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v 1.14.3

    - name: Install dependencies
      run: |
        if [ -f "Podfile" ]; then
          pod install
        elif [ -f "YTMusicUltimate/Podfile" ]; then
          cd YTMusicUltimate
          pod install
        else
          echo "ERROR: No Podfile found!"
          exit 1
        fi

    - name: Build unsigned IPA
      run: |
        if [ -f "YTMusicUltimate/Podfile" ]; then
          cd YTMusicUltimate
        fi
        
        xcodebuild -workspace YTMusicUltimate.xcworkspace \
                   -scheme YTMusicUltimate \
                   -configuration Release \
                   -destination 'generic/platform=iOS' \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   clean build \
                   CONFIGURATION_BUILD_DIR=./build

    - name: Package IPA
      run: |
        if [ -f "YTMusicUltimate/Podfile" ]; then
          APP_PATH="YTMusicUltimate/build/YTMusicUltimate.app"
        else
          APP_PATH="build/YTMusicUltimate.app"
        fi
        
        mkdir Payload
        cp -r "$APP_PATH" Payload/
        zip -r YTMusicUltimate.ipa Payload

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: YTMusicUltimate_Unsigned.ipa
        path: YTMusicUltimate.ipa
