name: Build YTMusicUltimate IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug directory structure
      run: |
        echo "Current directory: $PWD"
        echo "Contents:"
        ls -la
        echo "YTMusicUltimate directory:"
        ls -la YTMusicUltimate || echo "No YTMusicUltimate folder found"

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.0  # Use specific version to avoid issues

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v 1.14.3

    - name: Install dependencies
      run: |
        if [ -d "YTMusicUltimate" ]; then
          cd YTMusicUltimate
          pod install
        else
          pod install
        fi

    - name: Build unsigned IPA
      run: |
        if [ -d "YTMusicUltimate" ]; then
          cd YTMusicUltimate
          xcodebuild -workspace YTMusicUltimate.xcworkspace \
                     -scheme YTMusicUltimate \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     clean build \
                     CONFIGURATION_BUILD_DIR=./build
        else
          xcodebuild -workspace YTMusicUltimate.xcworkspace \
                     -scheme YTMusicUltimate \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     clean build \
                     CONFIGURATION_BUILD_DIR=./build
        fi

    - name: Package IPA
      run: |
        if [ -d "YTMusicUltimate" ]; then
          mkdir Payload
          cp -r YTMusicUltimate/build/YTMusicUltimate.app Payload/
          zip -r YTMusicUltimate.ipa Payload
        else
          mkdir Payload
          cp -r build/YTMusicUltimate.app Payload/
          zip -r YTMusicUltimate.ipa Payload
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: YTMusicUltimate_Unsigned.ipa
        path: YTMusicUltimate.ipa
