name: Build YTMusicUltimate IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug directory structure
      run: |
        echo "Current directory: $PWD"
        ls -la
        echo "Folder check:"
        ls -d YTMusicUltimate || echo "No YTMusicUltimate folder"
        ls -d YouTubeMusicUltimate || echo "No YouTubeMusicUltimate folder"

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.0

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v 1.14.3

    - name: Install dependencies
      run: |
        # Auto-detect project folder
        if [ -d "YTMusicUltimate" ]; then
          cd YTMusicUltimate
        elif [ -d "YouTubeMusicUltimate" ]; then
          cd YouTubeMusicUltimate
        fi
        pod install

    - name: Build unsigned IPA
      run: |
        if [ -d "YTMusicUltimate" ]; then
          cd YTMusicUltimate
        elif [ -d "YouTubeMusicUltimate" ]; then
          cd YouTubeMusicUltimate
        fi
        
        xcodebuild -workspace YTMusicUltimate.xcworkspace \
                   -scheme YTMusicUltimate \
                   -configuration Release \
                   -destination 'generic/platform=iOS' \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   clean build \
                   CONFIGURATION_BUILD_DIR=./build

    - name: Package IPA
      run: |
        if [ -d "YTMusicUltimate" ]; then
          cp -r YTMusicUltimate/build/YTMusicUltimate.app .
        elif [ -d "YouTubeMusicUltimate" ]; then
          cp -r YouTubeMusicUltimate/build/YTMusicUltimate.app .
        else
          cp -r build/YTMusicUltimate.app .
        fi
        
        mkdir Payload
        mv YTMusicUltimate.app Payload/
        zip -r YTMusicUltimate.ipa Payload

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: YTMusicUltimate_Unsigned.ipa
        path: YTMusicUltimate.ipa
